/ex1
SELECT NAME
FROM CITY
WHERE POPULATION > 120000 AND COUNTRYCODE = 'USA'

/ex2
SELECT * FROM CITY
WHERE COUNTRYCODE = "JPN"

/ex3
SELECT CITY, STATE FROM STATION
  
/ex4
SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%'

/ex5
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '%A' OR CITY LIKE '%E' OR CITY LIKE '%I' OR CITY LIKE '%O' OR CITY LIKE '%U'

/ex6
SELECT DISTINCT CITY FROM STATION
WHERE NOT (CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%')

/ex7
SELECT NAME FROM EMPLOYEE
ORDER BY NAME ASC

/ex8
SELECT NAME FROM EMPLOYEE
WHERE SALARY >2000 AND MONTHS <10
ORDER BY EMPLOYEE_ID ASC

/ex9
SELECT PRODUCT_ID FROM PRODUCTS
WHERE LOW_FATS = 'Y' AND RECYCLABLE = 'Y' 

/ex10
SELECT NAME FROM CUSTOMER
WHERE REFEREE_ID != 2 OR REFEREE_ID IS NULL

/ex11
SELECT NAME, POPULATION, AREA FROM WORLD
WHERE AREA >=3000000 OR POPULATION >=25000000 

/ex12
SELECT DISTINCT AUTHOR_ID AS ID FROM VIEWS
WHERE AUTHOR_ID = VIEWER_ID
ORDER BY ID ASC;

/e13
SELECT PART, ASSEMBLY_STEP FROM PARTS_ASSEMBLY
WHERE FINISH_DATE IS NULL

/e14
select index from lyft_drivers
where yearly_salary <=30000 or yearly_salary>=70000
  
/e15
select advertising_channel from uber_advertising
where money_spent >100000 and year = 2019
